// Import createSlice from Redux Toolkit
import { createSlice } from "@reduxjs/toolkit";

// Define the initial state
const initialState = {
  number: 0, // Initial value for the number
  category: ["tech", "helth"], // Categories array
};

// Create the slice
const numberSlice = createSlice({
  name: "number", // Name of the slice
  initialState, // Initial state of the slice
  reducers: {
    // Reducer for incrementing the number
    increment: (state, action) => {
      state.number += action.payload; // Directly modify the state (RTK uses Immer for immutability)
    },
    // Reducer for decrementing the number
    decrement: (state, action) => {
      state.number -= action.payload; // Directly modify the state
    },
  },
});

// Export the action creators generated by createSlice
export const { increment, decrement } = numberSlice.actions;

// Export the reducer to be used in the store
export default numberSlice.reducer;
